FROM node:22.16.0-alpine AS build

WORKDIR /app

RUN npm cache clean --force

COPY package*.json .
RUN npm install --force
COPY . .
RUN npm run build

FROM nginx:latest as ngi

RUN apt update
RUN apt install -y vim
RUN rm -rf /etc/localtime
RUN ln -s /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

COPY --from=build  /app/dist/fast-tag/browser/ /usr/share/nginx/html/
COPY ./nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80